# -*- coding: utf-8 -*-
"""AI_Travel_Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nzrPto0sn898q402XdMnSS-pD0G6iWMu
"""

!pip install langchain duckduckgo-search huggingface_hub

!pip install transformers duckduckgo-search gradio

!pip install geopy

from transformers import pipeline
from duckduckgo_search import DDGS
import gradio as gr

generator = pipeline("text-generation", model="tiiuae/falcon-7b-instruct", max_new_tokens=300)



import requests
from geopy.geocoders import Nominatim

def get_accurate_weather(city_name):
    print(f"DEBUG: Searching for coordinates for '{city_name}'...")

    # 1. Get Coordinates
    # TIP: Change "travel_planner_ai" to something unique like "yourname_travel_agent"
    # to avoid being blocked by the service.
    geolocator = Nominatim(user_agent="my_unique_travel_agent_v1")
    location = geolocator.geocode(city_name)

    if not location:
        print("DEBUG: Location not found.")
        return f"⚠️ Could not find coordinates for '{city_name}'. Check spelling."

    print(f"DEBUG: Found location: {location.latitude}, {location.longitude}")

    # 2. Call Weather API
    url = f"https://api.open-meteo.com/v1/forecast?latitude={location.latitude}&longitude={location.longitude}&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=auto"

    try:
        print("DEBUG: Calling Open-Meteo API...")
        response = requests.get(url).json()

        if 'error' in response:
            return f"API Error: {response['reason']}"

        daily = response['daily']

        # 3. Format Output
        weather_report = f"### 🌦️ Weather Forecast for {city_name}\n"
        for i in range(3): # Next 3 days
            date = daily['time'][i]
            max_temp = daily['temperature_2m_max'][i]
            rain_prob = daily['precipitation_probability_max'][i]
            weather_report += f"- **{date}**: Max {max_temp}°C, Rain {rain_prob}%\n"

        print("DEBUG: Weather fetched successfully.")
        return weather_report

    except Exception as e:
        print(f"DEBUG: Error occurred - {e}")
        return f"Error fetching weather: {str(e)}"

def plan_trip(destination, days, interests):
    prompt = f"Plan a {days}-day trip to {destination} focusing on {interests}. Include historical sites, local food, and fun activities."
    itinerary = generator(prompt)[0]["generated_text"]

    weather = get_accurate_weather(destination)
    return f"*Itinerary:\n{itinerary}\n\n🌦️ **Weather Info:*\n{weather}"

gr.Interface(
    fn=plan_trip,
    inputs=[
        gr.Textbox(label="Destination (e.g. Rome)"),
        gr.Slider(1, 10, step=1, label="Number of Days"),
        gr.Textbox(label="Interests (e.g. food, history, culture)")
    ],
    outputs="markdown",
    title="🧳 Free AI Travel Planner",
    description="Uses Falcon-7B and DuckDuckGo to plan a trip and show weather"
).launch()